name: Build Native Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libz-dev zlib1g-dev curl unzip
          curl -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz --output graalvm.tar.gz
          tar -xzf graalvm.tar.gz
          export PATH=$PATH:/path/to/graalvm-ce-java11-21.3.0/bin
          sdk install maven
      - name: Build Native Executable
        run: mvn clean package -Pnative
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: native-executable
          path: target/wtf-chatgpt-0.0.1-runner
